######################################################################
# Automatically generated by qmake (3.1) Tue Jan 14 21:12:00 2025
######################################################################

TEMPLATE = app
TARGET = MagicManager
SOURCES += \
    main.cpp \
    ./ViewControllers/CardExplorer.cpp \
    ./DataModel/Card.cpp \
    ./DataModel/Collection.cpp \
    ./AssetManagers/DatabaseManager.cpp

# Directories
QT += core gui widgets network multimedia sql charts qml quick